# Generated by Django 3.0.8 on 2020-10-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=70)),
                ('mobile', models.IntegerField()),
                ('home_address', models.TextField()),
                ('address', models.TextField()),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
