# Generated by Django 3.0.8 on 2020-11-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201104_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('img', models.ImageField(upload_to='')),
                ('cat', models.CharField(max_length=70)),
            ],
        ),
    ]
