# Generated by Django 3.0.8 on 2020-11-05 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userservices'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserServices',
            new_name='UserService',
        ),
        migrations.RenameField(
            model_name='userservice',
            old_name='cat',
            new_name='categ',
        ),
    ]
