# Generated by Django 3.0.8 on 2020-11-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201105_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=70)),
                ('mobile', models.CharField(max_length=10)),
                ('address', models.TextField(max_length=150)),
                ('categ', models.CharField(max_length=70)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='home_address',
        ),
    ]
