# Generated by Django 3.0.8 on 2020-11-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201113_0833'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_service', models.CharField(max_length=70)),
                ('booking_date', models.DateField()),
                ('booking_time', models.TimeField()),
                ('expected_date', models.DateField()),
                ('expected_time', models.TimeField()),
                ('total_charge', models.CharField(max_length=70)),
                ('extra_charge', models.CharField(max_length=70)),
                ('vendor', models.CharField(max_length=15)),
                ('requestor', models.CharField(max_length=15)),
            ],
        ),
    ]
