# Generated by Django 3.0.8 on 2020-11-16 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_bookedservices'),
    ]

    operations = [
        migrations.AddField(
            model_name='userservice',
            name='price',
            field=models.IntegerField(default=100),
        ),
    ]
