# Generated by Django 3.0.8 on 2020-11-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_userservice_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='userservice',
            name='desc',
            field=models.CharField(default='dfgdfg', max_length=1000),
        ),
    ]
