# Generated by Django 3.0.8 on 2020-11-30 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_userservice_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userservice',
            old_name='desc',
            new_name='description',
        ),
    ]
