# Generated by Django 3.0.8 on 2020-12-02 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20201202_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedservices',
            name='status',
            field=models.CharField(default='Booked', max_length=100),
        ),
        migrations.AddField(
            model_name='bookedservices',
            name='token',
            field=models.CharField(default='fsgsh4886h5ssr454$%^@', max_length=100),
        ),
    ]
